#!/bin/bash

if (( $# < 2 ))
then echo "usage: legals width modulus [y [ x [ncpus [memsize [height [keep]]]]]]"; exit
fi

width=$1
modidx=$2
if (( $# >= 3 )); then      y=$3; else y=0; fi
if (( $# >= 4 )); then      x=$4; else x=0; fi
if (( $# >= 5 )); then  ncpus=$5; else ncpus=1; fi
if (( $# >= 6 )); then  msize=$6; else msize=500M; fi
if (( $# >= 7 )); then height=$7; else height=$width; fi
if (( $# >= 8 )); then   keep=$8; else keep=0; fi

obsolete=""
tmpcpu="tmp.cpu"
bin="/home/tromp/golegal"
echo "$bin/start $width $modidx"
if ((x == 0 && y == 0)); then $bin/start $width $modidx; fi
while ((y < height)); do
  for (( cpu=0; cpu < ncpus; cpu++ )); do
    echo "time $bin/legal $width $modidx $y $x $ncpus $cpu $msize &> $tmpcpu$cpu"
          time $bin/legal $width $modidx $y $x $ncpus $cpu $msize &> $tmpcpu$cpu || kill -9 $$ &
  done
  wait
  cat $tmpcpu*
  rm $tmpcpu*
  if [[ $obsolete != "" ]]; then rm state.$width.$modidx.$obsolete.*; fi
  if (( keep == 0 || x != 0 )); then obsolete=$y.$x; else obsolete=""; fi
  ((x += 1))
  if ((x == width)); then ((x = 0)); ((y += 1)); fi
  date
done
